/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TechnicalEvidenceRouteImport } from './routes/technical-evidence'
import { Route as SubmittalsRouteImport } from './routes/submittals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlumbingSystemRouteImport } from './routes/plumbing-system'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FieldAnalysisRouteImport } from './routes/field-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SubmittalsIdRouteImport } from './routes/submittals.$id'
import { Route as RfisIdRouteImport } from './routes/rfis.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as FilesIdRouteImport } from './routes/files.$id'
import { Route as ApprovalsIdRouteImport } from './routes/approvals.$id'
import { Route as ProjectsIdTeamRouteImport } from './routes/projects.$id.team'
import { Route as ProjectsIdModelsRouteImport } from './routes/projects.$id.models'
import { Route as ProjectsIdIssuesRouteImport } from './routes/projects.$id.issues'
import { Route as ProjectsIdFilesRouteImport } from './routes/projects.$id.files'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalEvidenceRoute = TechnicalEvidenceRouteImport.update({
  id: '/technical-evidence',
  path: '/technical-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittalsRoute = SubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingSystemRoute = PlumbingSystemRouteImport.update({
  id: '/plumbing-system',
  path: '/plumbing-system',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldAnalysisRoute = FieldAnalysisRouteImport.update({
  id: '/field-analysis',
  path: '/field-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const SubmittalsIdRoute = SubmittalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubmittalsRoute,
} as any)
const RfisIdRoute = RfisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RfisRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IssuesRoute,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FilesRoute,
} as any)
const ApprovalsIdRoute = ApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApprovalsRoute,
} as any)
const ProjectsIdTeamRoute = ProjectsIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdModelsRoute = ProjectsIdModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdIssuesRoute = ProjectsIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdFilesRoute = ProjectsIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/files': typeof FilesRouteWithChildren
  '/help': typeof HelpRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/plumbing-system': typeof PlumbingSystemRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rfis': typeof RfisRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submittals': typeof SubmittalsRouteWithChildren
  '/technical-evidence': typeof TechnicalEvidenceRoute
  '/trust': typeof TrustRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/files/$id': typeof FilesIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/rfis/$id': typeof RfisIdRoute
  '/submittals/$id': typeof SubmittalsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/models': typeof ProjectsIdModelsRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/files': typeof FilesRouteWithChildren
  '/help': typeof HelpRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/plumbing-system': typeof PlumbingSystemRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfis': typeof RfisRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submittals': typeof SubmittalsRouteWithChildren
  '/technical-evidence': typeof TechnicalEvidenceRoute
  '/trust': typeof TrustRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/files/$id': typeof FilesIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/rfis/$id': typeof RfisIdRoute
  '/submittals/$id': typeof SubmittalsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/models': typeof ProjectsIdModelsRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/files': typeof FilesRouteWithChildren
  '/help': typeof HelpRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/plumbing-system': typeof PlumbingSystemRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rfis': typeof RfisRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submittals': typeof SubmittalsRouteWithChildren
  '/technical-evidence': typeof TechnicalEvidenceRoute
  '/trust': typeof TrustRoute
  '/approvals/$id': typeof ApprovalsIdRoute
  '/files/$id': typeof FilesIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/rfis/$id': typeof RfisIdRoute
  '/submittals/$id': typeof SubmittalsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/issues': typeof ProjectsIdIssuesRoute
  '/projects/$id/models': typeof ProjectsIdModelsRoute
  '/projects/$id/team': typeof ProjectsIdTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/dashboard'
    | '/field-analysis'
    | '/files'
    | '/help'
    | '/issues'
    | '/login'
    | '/members'
    | '/notifications'
    | '/plumbing-system'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/rfis'
    | '/settings'
    | '/submittals'
    | '/technical-evidence'
    | '/trust'
    | '/approvals/$id'
    | '/files/$id'
    | '/issues/$id'
    | '/members/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/rfis/$id'
    | '/submittals/$id'
    | '/projects/'
    | '/projects/$id/files'
    | '/projects/$id/issues'
    | '/projects/$id/models'
    | '/projects/$id/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/dashboard'
    | '/field-analysis'
    | '/files'
    | '/help'
    | '/issues'
    | '/login'
    | '/members'
    | '/notifications'
    | '/plumbing-system'
    | '/profile'
    | '/reset-password'
    | '/rfis'
    | '/settings'
    | '/submittals'
    | '/technical-evidence'
    | '/trust'
    | '/approvals/$id'
    | '/files/$id'
    | '/issues/$id'
    | '/members/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/rfis/$id'
    | '/submittals/$id'
    | '/projects'
    | '/projects/$id/files'
    | '/projects/$id/issues'
    | '/projects/$id/models'
    | '/projects/$id/team'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/dashboard'
    | '/field-analysis'
    | '/files'
    | '/help'
    | '/issues'
    | '/login'
    | '/members'
    | '/notifications'
    | '/plumbing-system'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/rfis'
    | '/settings'
    | '/submittals'
    | '/technical-evidence'
    | '/trust'
    | '/approvals/$id'
    | '/files/$id'
    | '/issues/$id'
    | '/members/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/rfis/$id'
    | '/submittals/$id'
    | '/projects/'
    | '/projects/$id/files'
    | '/projects/$id/issues'
    | '/projects/$id/models'
    | '/projects/$id/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FieldAnalysisRoute: typeof FieldAnalysisRoute
  FilesRoute: typeof FilesRouteWithChildren
  HelpRoute: typeof HelpRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PlumbingSystemRoute: typeof PlumbingSystemRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfisRoute: typeof RfisRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubmittalsRoute: typeof SubmittalsRouteWithChildren
  TechnicalEvidenceRoute: typeof TechnicalEvidenceRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-evidence': {
      id: '/technical-evidence'
      path: '/technical-evidence'
      fullPath: '/technical-evidence'
      preLoaderRoute: typeof TechnicalEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submittals': {
      id: '/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof SubmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing-system': {
      id: '/plumbing-system'
      path: '/plumbing-system'
      fullPath: '/plumbing-system'
      preLoaderRoute: typeof PlumbingSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-analysis': {
      id: '/field-analysis'
      path: '/field-analysis'
      fullPath: '/field-analysis'
      preLoaderRoute: typeof FieldAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/submittals/$id': {
      id: '/submittals/$id'
      path: '/$id'
      fullPath: '/submittals/$id'
      preLoaderRoute: typeof SubmittalsIdRouteImport
      parentRoute: typeof SubmittalsRoute
    }
    '/rfis/$id': {
      id: '/rfis/$id'
      path: '/$id'
      fullPath: '/rfis/$id'
      preLoaderRoute: typeof RfisIdRouteImport
      parentRoute: typeof RfisRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/approvals/$id': {
      id: '/approvals/$id'
      path: '/$id'
      fullPath: '/approvals/$id'
      preLoaderRoute: typeof ApprovalsIdRouteImport
      parentRoute: typeof ApprovalsRoute
    }
    '/projects/$id/team': {
      id: '/projects/$id/team'
      path: '/team'
      fullPath: '/projects/$id/team'
      preLoaderRoute: typeof ProjectsIdTeamRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/models': {
      id: '/projects/$id/models'
      path: '/models'
      fullPath: '/projects/$id/models'
      preLoaderRoute: typeof ProjectsIdModelsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/issues': {
      id: '/projects/$id/issues'
      path: '/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof ProjectsIdIssuesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/files': {
      id: '/projects/$id/files'
      path: '/files'
      fullPath: '/projects/$id/files'
      preLoaderRoute: typeof ProjectsIdFilesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ApprovalsRouteChildren {
  ApprovalsIdRoute: typeof ApprovalsIdRoute
}

const ApprovalsRouteChildren: ApprovalsRouteChildren = {
  ApprovalsIdRoute: ApprovalsIdRoute,
}

const ApprovalsRouteWithChildren = ApprovalsRoute._addFileChildren(
  ApprovalsRouteChildren,
)

interface FilesRouteChildren {
  FilesIdRoute: typeof FilesIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesIdRoute: FilesIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface IssuesRouteChildren {
  IssuesIdRoute: typeof IssuesIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIdRoute: IssuesIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdFilesRoute: typeof ProjectsIdFilesRoute
  ProjectsIdIssuesRoute: typeof ProjectsIdIssuesRoute
  ProjectsIdModelsRoute: typeof ProjectsIdModelsRoute
  ProjectsIdTeamRoute: typeof ProjectsIdTeamRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdFilesRoute: ProjectsIdFilesRoute,
  ProjectsIdIssuesRoute: ProjectsIdIssuesRoute,
  ProjectsIdModelsRoute: ProjectsIdModelsRoute,
  ProjectsIdTeamRoute: ProjectsIdTeamRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RfisRouteChildren {
  RfisIdRoute: typeof RfisIdRoute
}

const RfisRouteChildren: RfisRouteChildren = {
  RfisIdRoute: RfisIdRoute,
}

const RfisRouteWithChildren = RfisRoute._addFileChildren(RfisRouteChildren)

interface SubmittalsRouteChildren {
  SubmittalsIdRoute: typeof SubmittalsIdRoute
}

const SubmittalsRouteChildren: SubmittalsRouteChildren = {
  SubmittalsIdRoute: SubmittalsIdRoute,
}

const SubmittalsRouteWithChildren = SubmittalsRoute._addFileChildren(
  SubmittalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FieldAnalysisRoute: FieldAnalysisRoute,
  FilesRoute: FilesRouteWithChildren,
  HelpRoute: HelpRoute,
  IssuesRoute: IssuesRouteWithChildren,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PlumbingSystemRoute: PlumbingSystemRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RfisRoute: RfisRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubmittalsRoute: SubmittalsRouteWithChildren,
  TechnicalEvidenceRoute: TechnicalEvidenceRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
