// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdaksgsulonxwkndgada.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYWtzZ3N1bG9ueHdrbmRnYWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE3MzYwOTAsImV4cCI6MjA5NzMxMjA5MH0.gXNcvE8YppoA-gzxK167P2wlPhPpe4l4yOf_borAQMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});